on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          labels: |
            com.github.actions.name=docker
            com.github.actions.description=Build and push Docker images
            com.github.actions.icon=docker
            com.github.actions.color=blue
          platforms: ${{ matrix.platform }}
          builder: auto

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build --platform ${{ matrix.platform }} -t joke-app .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/joke-app
